default_platform :ios

platform :ios do

  desc "Submit a new Beta Build to Crashlytic"
  desc "This will also make sure the profile is up to date"
  lane :beta do

    unlock_keychain(
      path: ENV["KEYCHAIN_PATH"],
      password: ENV["KEYCHAIN_PASSWORD"]
    )

    import_certificate(
      keychain_name: ENV["KEYCHAIN_NAME"], 
      certificate_path: ENV["CERTIFICATE_PATH"], 
      certificate_password: ENV["CERTIFICATE_PASSWORD"]
    )

    sigh(
      adhoc: true,
      output_path: ENV["PROVISIONING_OUTPUT_PATH"]
    )

  end

end
